### ISSUE TITLE
Load image url

### ISSUE THREAD

**Issue by mittalyashu** [GoogleChromeLabs/squoosh#557] opened 2019-04-21 08:06 UTC
**Is your feature request related to a problem? Please describe.**
In the current version of an application, it only allows us to add local images by drag and drop, or image selector.

But squooshing a remote image will also be helpful.

**Describe the solution you'd like**

Allowing users to paste an image URL, then the image can be downloaded locally as a cache or as a proper file on desktop _(or download location)_ and then the compression of the image can continue.

**Comment by jakearchibald** [comment] 2019-04-21 10:27
Dupe of https://github.com/GoogleChromeLabs/squoosh/issues/330

**Closed by jakearchibald** 2019-04-21 10:27 UTC
