### ISSUE TITLE
Reduce palette not working

### ISSUE THREAD

**Issue by rin3s** [GoogleChromeLabs/squoosh#946] opened 2021-01-22 10:36 UTC
**Describe the bug**
When attempting to use the **reduce palette** feature (on the online version at least), you get an error: "Processing error: ReferenceError: __dirname is not defined"

**To Reproduce**
1. Go to https://squoosh.app/
2. Use one of the existing images.
3. Try to use reduce palette.
4. See error.

**Expected behavior**
To be able to use the reduce palette feature, to reduce the colors.

**Version:**
 - OS w/ version: Windows 10
 - Browser w/ version: Chrome Version 87.0.4280.141 / Firefox 84.0.2

**Comment by surma** [comment] 2021-01-22 11:03
I can’t reproduce this in Chrome on MacOS. @RReverser can you give this a try?

**Comment by rin3s** [comment] 2021-01-22 11:18
Had a colleague test on Chrome on MacOS, and she was getting the same error, and another colleague with Windows 10 and Chrome as well.

This was still working yesterday, but it stopped working after refreshing the page today after getting an "Update is available" notification.
![squoosh_error](https://user-images.githubusercontent.com/38850585/105484549-cb9a9280-5cab-11eb-8480-2e2ca0b06d4a.jpg)

**Comment by jakearchibald** [comment] 2021-01-22 11:29
I can recreate this. I'm going to roll back live.

**Comment by jakearchibald** [comment] 2021-01-22 11:32
Live is rolling back to 5d0c856. Assigning to @RReverser since it was the codec rebuild that seemed to cause this.

**Comment by jakearchibald** [comment] 2021-01-22 11:32
@rin3s thanks for reporting this! The fix (well, rollback) should be live in a few minutes.

**Comment by rin3s** [comment] 2021-01-22 12:09
@jakearchibald Awesome.
Live is working now again, thanks!

**Comment by RReverser** [comment] 2021-01-22 12:32
That's very strange, but yeah, I can see something relevant in the diff on #935:

```
- for(u in e)e.hasOwnProperty(u)&&(t[u]=e[u]);var v="",ba;v=self.location.href;
+ for(u in e)e.hasOwnProperty(u)&&(t[u]=e[u]);var v="",ba,ca,da,ea;v=__dirname+"/";
```

I wonder what the actual underlying change was that caused this.

**Comment by RReverser** [comment] 2021-01-22 12:39
Logging shows that `ENVIRONMENT=worker` is set correctly for `imagequant.js`, so maybe this is an Emscripten issue and it still uses `__dirname` when it shouldn't?

**Comment by RReverser** [comment] 2021-01-22 12:43
OH MY GOD @surma 😂

https://github.com/GoogleChromeLabs/squoosh/blob/6117c9dd267e800e93f7435c0acb93e5b344a221/codecs/imagequant/Makefile#L14-L43

I somehow missed this in review of #875 too 😂 

For each file, it compiles twice - first with correct environment, and second one that overwrites it with `ENVIRONMENT=node`.

**Comment by RReverser** [comment] 2021-01-22 12:45
We probably should add some sort of CI task that makes sure any output files are newer than Makefiles, to ensure that codecs are always rebuilt and tested with the latest Makefile changes.

**Comment by RReverser** [comment] 2021-01-22 12:48
Fixed in https://github.com/GoogleChromeLabs/squoosh/pull/947.

**Closed as completed** 2021-01-22 13:13 UTC
