### ISSUE TITLE
Invalid image on all images

### ISSUE THREAD

**Issue by oliviernt** [GoogleChromeLabs/squoosh#285] opened 2018-11-14 11:30 UTC
I'm using Brave 1.0.61 (Chromium 70.0.3538.80) on Android 7 and everytime I try to select an image from my phone, I get the "Invalid image" error.

**Comment by oliviernt** [comment] 2018-11-14 11:33
Example image that doesn't work: ![img-20181109-wa0001](https://user-images.githubusercontent.com/162120/48480044-70d29a00-e809-11e8-8e41-0d2847ae2476.jpg)

**Comment by surma** [comment] 2018-11-14 16:21
I can reproduce not being able to load this image in Chrome and Brave. I can also successfully load  other images in Brave. So this issue seems unrelated to Brave and more related to the image at hand.

**Comment by oliviernt** [comment] 2018-11-14 16:38
Could you provide me with one of your images so I can test it? I've tried with multiple images from different sources but was unable to get it to work on my phone. It did work on my laptop though with that same image.

**Comment by surma** [comment] 2018-11-14 16:52
Do the demo images not work for you either?

**Comment by jakearchibald** [comment] 2018-11-14 17:20
I can open the above image in Chrome Android fwiw.

**Comment by oliviernt** [comment] 2018-11-14 17:46
@surma no. No image has worked so far on my phone...

**Comment by jakearchibald** [comment] 2018-11-14 22:45
Same version of Brave, I can open all the demo images. But I'm on Android 9. Guess I need to find a test device.

@surma 

> I can reproduce not being able to load this image in Chrome and Brave.

Is this a typo, or can you reproduce the issue?

**Comment by surma** [comment] 2018-11-14 23:38
No, the attached image from @oliviernt does indeed not load for me on mobile (it does on desktop 🤔)

**Comment by oliviernt** [comment] 2018-11-15 06:12
I'm on a Honor 5x with a Lineage OS custom ROM if this is of any help. Maybe it's possible to reproduce in a virtualized environment!? I'll see of I find time to setup something...

**Comment by biovolt** [comment] 2018-11-22 05:59
I get this when the ext is png but it is actually a jpg

**Comment by surma** [comment] 2018-11-22 11:06
> I get this when the ext is png but it is actually a jpg

Oh, interesting. That is surprising, because [we really on sniffing](https://github.com/GoogleChromeLabs/squoosh/blob/adf6d3c60d41f2ebe9a1fe65b505fe37c2784a6c/src/codecs/decoders.ts#L8) rather than file extensions...

**Comment by biovolt** [comment] 2018-11-23 05:13
It works in chrome but fails in Firefox Quantum 63.0.3 64bit
This is the image.
![3e1b35180899e8a5aa51e18864af0a2d576dd5d0_ft banner 1](https://user-images.githubusercontent.com/1982739/48929213-2e871800-eeef-11e8-87e0-a3eb70fc4d61.png)

**Comment by jakearchibald** [comment] 2018-11-23 06:31
Might be fixed in Firefox nightly https://bugzilla.mozilla.org/show_bug.cgi?id=1497925

**Comment by surma** [comment] 2020-12-10 11:01
All these images load now 🎉

**Closed by surma** 2020-12-10 11:01 UTC
Labels: bug
