### ISSUE TITLE
jxl effort slide give unpredictable results

### ISSUE THREAD

**Issue by brigazvi** [GoogleChromeLabs/squoosh#1109] opened 2021-07-25 23:06 UTC
on jxl, effort 1 beats effort 6, in a lot of scenarios, in terms of file size (especially in progressive decoding mode). even in lossless. it takes much less time but it gives smaller files.

**To Reproduce**
1. open an image.
2. choose jxl.
3. turn progressive rendering on.
3. choose effort 1.
4. choose effort 6.
5. compare them.
6. fill the difference.
7. ask yourself: why?

**Expected behavior**
higher values should give smaller file size, especially in lossless, when file size is the only metric, in cost of longer encoding time.

**Version:**
 - OS w/ version: windows 10 home 21h1
 - Browser w/ version: microsoft edge 92.

**Comment by surma** [comment] 2021-07-25 23:31
cc @jonsneyers @veluca93

**Comment by surma** [comment] 2021-07-25 23:34
Note that this is only reproducible with “Progressive Rendering” enabled, which I _believe_ is a known bug in the current JPEG XL encoder.

**Comment by ziemek99** [comment] 2021-08-28 00:42
This is known JPEG XL bug, see: [wg1/jpeg-xl#204](https://gitlab.com/wg1/jpeg-xl/-/issues/204), libjxl/libjxl#235.
I suggest closing this issue since [libjxl](https://github.com/libjxl/libjxl) is here at fault, not Squoosh.

**Closed as completed** 2021-08-28 06:59 UTC
