### ISSUE TITLE
Need Bulk Compression

### ISSUE THREAD

**Issue by imerfanahmed** [GoogleChromeLabs/squoosh#879] opened 2020-12-08 12:47 UTC
Clearly Squoosh is a  wonderfull Project,
But it hasnt any bulk optimization feature,
The clear points are
1.Need user-customized settings for default operation, and then bulk compression output.

**Comment by surma** [comment] 2020-12-08 13:05
Working on that. Also duplicate of #301

**Closed as completed by surma** 2020-12-08 13:05 UTC
