### ISSUE TITLE
ImagePool closes itself if inactive

### ISSUE THREAD

**Issue by theKashey** [GoogleChromeLabs/squoosh#1098] opened 2021-07-11 07:36 UTC
**Describe the bug**
Any _delay_ between `new ImagePool()` and `imagePool.ingestImage` will cause poll termination

**To Reproduce**
```js
const imagePool = new ImagePool();
await 1;
const image = imagePool.ingestImage(sourceData);
// ^ exception will be thrown - as `this.jobQueue.writable` is closed.
```

**Expected behavior**
Pool closes only when user calls `imagePool.close()`

**Version:**
@squoosh/lib: 0.3.1

**Additional context, screenshots, screencasts**
After being created `ImagePool` enters `_readLoop` and if no command will be issued in the next tick - it auto terminates.

https://github.com/GoogleChromeLabs/squoosh/blob/99f2286a737f52831aef0f77699def844bd7a170/libsquoosh/src/worker_pool.js#L48

**Comment by surma** [comment] 2021-07-19 12:10
Hey @theKashey,

what Node version are you using? I can’t reproduce this bug. Even waiting for a whole second does not break the library for me. I used this code to test:

```js
import { ImagePool } from './build/index.js';

const imagePool = new ImagePool();
await new Promise(resolve => setTimeout(resolve, 1000));
const imagePath = '/Users/surma/Downloads/squoosh.png';
const image = imagePool.ingestImage(imagePath);
await image.decoded;
const encodeOptions = {
  mozjpeg: {quality: 10},
};
await image.encode(encodeOptions);
console.log(await image.encodedWith.mozjpeg);
await imagePool.close();
```

The code snippet you linked to, where `_terminateAll()` is called, is only called once the `jobQueue` is _closed_. If there is no job in the queue, await `reader.read()` will block. So there is no auto-closing.

**Comment by theKashey** [comment] 2021-07-20 00:23
Yep, you are absolutely right
- created a sandbox(`node 14` and squoosh 0.3.1) https://codesandbox.io/s/frosty-tree-r669m?file=/src/index.js and it's working perfectly
- Running the same locally with `node 16` - working perfectly
- Running again [the code which caused the problem](https://github.com/theKashey/holistic-image/blob/e9825c94731e03138bc7dd41710df0475118f612/src/generator/derive-images.ts#L59) in the first time - and it still works perfectly

Please give me some time to break things a little more thoughtfully and be back to you with a reproducible example.

**Comment by jakearchibald** [comment] 2023-01-03 14:42
Unfortunately, due to a few people leaving the team, and staffing issues resulting from the current economic climate (ugh), the CLI and libsquoosh packages are no longer actively maintained. I know that sucks, but there simply isn't the time & people to work on this. If anyone from the community wants to fork it, you have my blessing. The [squoosh.app](https://squoosh.app/) web app will continue to be supported and improved.

**Closed as not planned by jakearchibald** 2023-01-03 14:42 UTC
