### ISSUE TITLE
Multiple image upload using the web user interface.

### ISSUE THREAD

**Issue by pazlydev** [GoogleChromeLabs/squoosh#1340] opened 2023-03-07 11:07 UTC
**Problem**
At the moment, on https://squoosh.app/ it is possible to process only one image the time using the user interface. 

**Describe the solution you'd like**
It would be very useful to be able to upload multiple image, perhaps an entire folder on the web user interface https://squoosh.app/  
The preview should display the list of images one blow the other. Each image should allow the slider for comparing before and after image quality. 

When uploading the set of image, the same transformation should apply to all image. The user will select a transformation configuration which will be applied to all the images that are loaded in the list. 

**Does other service/app have this feature?**
Uploading a folder is best exemplified by Netlify Drop https://app.netlify.com/drop/

**Additional context**

**Comment by jakearchibald** [comment] 2023-03-07 12:05
Dupe of https://github.com/GoogleChromeLabs/squoosh/issues/1259

**Closed as completed by jakearchibald** 2023-03-07 12:05 UTC
