### ISSUE TITLE
Bad memory management

### ISSUE THREAD

**Issue by fparedlo** [GoogleChromeLabs/squoosh#1094] opened 2021-07-07 19:00 UTC
**Describe the bug**
Memory and virtual memory full usage causes the process to crash.

**Expected behavior**
I would expect a better usage of the memory to avoid this issue, maybe a memory limit cap.

**Version:**
 - OS w/ version: Windows 10
 - Browser w/ version : not applicable -  squoosh/cli 
 - Node version: v14.16.0
 - npm version: 6.14.11

**Additional context, screenshots, screencasts**
[youtube demo](https://youtu.be/bXtKj2tvOzw)

**Comment by surma** [comment] 2021-07-07 22:27
Duplicate of #1012

**Closed as completed by surma** 2021-07-07 22:27 UTC
