### ISSUE TITLE
Let user set his own default on the pwa app

### ISSUE THREAD

**Issue by chromaniac2** [GoogleChromeLabs/squoosh#1144] opened 2021-09-06 07:51 UTC
**Is your feature request related to a problem? Please describe.**
By default, Squoosh offers MozJPEG at 75% optimization. If I prefer to output WebP for a bunch of images, I have to change the setting on every image load. 

**Describe the solution you'd like**
A new option that lets the user define a new default image output setting which is saved on the PWA. 

**Does other service/app have this feature?**
NA

**Additional context**
NA

**Comment by jakearchibald** [comment] 2021-09-06 09:06
Dupe of https://github.com/GoogleChromeLabs/squoosh/issues/430

**Closed as completed by jakearchibald** 2021-09-06 09:06 UTC
