### ISSUE TITLE
Support High Efficiency Image File Format

### ISSUE THREAD

**Issue by kaihendry** [GoogleChromeLabs/squoosh#1360] opened 2023-04-05 03:10 UTC
**Is your feature request related to a problem? Please describe.**

Source decoding error: Error: Couldn't decode image on a HIF image: https://s.natalian.org/2023-04-05/milan2023.HIF

**Describe the solution you'd like**

Support for https://en.wikipedia.org/wiki/High_Efficiency_Image_File_Format

**Does other service/app have this feature?**

Google Photos https://photos.app.goo.gl/JEadX4KBqViVFXdm9

**Comment by jakearchibald** [comment] 2023-04-05 05:30
Dupe of https://github.com/GoogleChromeLabs/squoosh/issues/733

**Closed as completed by jakearchibald** 2023-04-05 05:30 UTC

**Comment by markstos** [comment] 2023-06-12 15:12
#733 was closed citing licensing, but there's an unaddressed follow-up noting the license is free for non-commercial use. Since Squoosh is free and open source, could this still be done? Or "no", because some use of Squoosh by Google would be considered Commercial?
