### ISSUE TITLE
Drag and Drop Multiple Photos

### ISSUE THREAD

**Issue by drveresh** [GoogleChromeLabs/squoosh#576] opened 2019-05-04 03:25 UTC
**Is your feature request related to a problem? Please describe.**
No, It is a new feature, to process and optimize multiple photos at https://squoosh.app/

**Describe the solution you'd like**
We need a feature to drag and drop multiple photos

**Does other service/app have this feature?**
Yes, it is like a basic use case that many users have >1 photos to optimize.

**Comment by jakearchibald** [comment] 2019-05-04 11:58
Dupe of #301

**Closed by jakearchibald** 2019-05-04 11:58 UTC
