### ISSUE TITLE
Edit 100 images

### ISSUE THREAD

**Issue by Camilo517** [GoogleChromeLabs/squoosh#454] opened 2019-02-08 12:05 UTC
Hello, I would like to know if there is any way to edit about 100 images without having to go one by one. I want to give a same parameter to all. Thank you

My idea is to compress all the images of my WordPress

**Comment by jakearchibald** [comment] 2019-02-08 12:40
Duplicate of https://github.com/GoogleChromeLabs/squoosh/issues/301

**Closed by jakearchibald** 2019-02-08 12:40 UTC
