### ISSUE TITLE
Runtime Error

### ISSUE THREAD

**Issue by jadsongmatos** [GoogleChromeLabs/squoosh#919] opened 2020-12-21 15:01 UTC
some images do not load. does anyone know how i can solve this ?

![image](https://user-images.githubusercontent.com/50336793/102801045-76f5b600-4393-11eb-8c96-43f27d2dc4bc.png)

```
npx @squoosh/cli --jxl '{"speed":1,"quality":100,"progressive":true,"epf":-1,"nearLossless":0,"lossyPalette":true}' 45.png
npx: installed 2 in 2.31s
0/1 / ▐▨▨▨▨▨╌╌╌╌╌▌ Encoding (6 threads)
 45.png: 35.92MBundefined
Worker error:  Error [RuntimeError]: abort(RuntimeError: abort(undefined). Build with -s ASSERTIONS=1 for more info.). Build with -s ASSERTIONS=1 for more info.
    at process.w (C:\Users\Ti\AppData\Roaming\npm-cache\_npx\23976\node_modules\@squoosh\cli\build\index.js:7:376640)
    at process.emit (events.js:327:22)
    at processPromiseRejections (internal/process/promises.js:209:33)
0/1 - ▐▨▨▨▨▨╌╌╌╌╌▌ Encoding (6 threads)
 45.png: 35.92MB
```

**Comment by surma** [comment] 2020-12-22 01:13
Can you attach one of these images?

**Comment by jadsongmatos** [comment] 2020-12-22 12:48
> Can you attach one of these images?

I can't attach here over 10mb

I will post the image link on google drive

https://drive.google.com/file/d/1PVTK2lWGNoK3kKdXcSkMiHxnJc8DxJg0/view?usp=sharing

**Comment by surma** [comment] 2020-12-22 12:55
Ah it’s a big image. Yeah, that is most likely the cause. Technically, there is nothing keeping us from handing ~150MB of RGBA data, but I know that big images currently cause issues.

**Comment by surma** [comment] 2020-12-22 14:33
(Side question: Does it succeed with codecs other than JXL as output? JXL is still somewhat unstable)

**Comment by jadsongmatos** [comment] 2020-12-22 14:52
mozJPEG, WEBP, JPG Browser and PNG Browser works

With AVIF being this error
```
npx @squoosh/cli --avif '{"maxQuantizer":63,"minQuantizer":33,"maxQuantizerAlpha":63,"minQuantizerAlpha":33,"subsample":1,"tileColsLog2":0,"tileRowsLog2":0,"speed":0}' 45.png
npx: installed 2 in 13.463s
0/1 - ▐▨▨▨▨▨╌╌╌╌╌▌ Encoding (6 threads)
 45.png: 35.92MBTypeError [ERR_INVALID_ARG_TYPE]: The "data" argument must be of type string or an instance of Buffer, TypedArray, or DataView. Received null
    at Object.writeFile (internal/fs/promises.js:510:5)
    at encodeFile (C:\Users\Ti\AppData\Roaming\npm-cache\_npx\20420\node_modules\@squoosh\cli\build\index.js:7:538294)
    at async MessagePort.<anonymous> (C:\Users\Ti\AppData\Roaming\npm-cache\_npx\20420\node_modules\@squoosh\cli\build\index.js:7:508874) {
  code: 'ERR_INVALID_ARG_TYPE'
}
Worker error:  Error [RuntimeError]: abort(TypeError [ERR_INVALID_ARG_TYPE]: The "data" argument must be of type string or an instance of Buffer, TypedArray, or DataView. Received null). Build with -s ASSERTIONS=1 for more info.
    at process.w (C:\Users\Ti\AppData\Roaming\npm-cache\_npx\20420\node_modules\@squoosh\cli\build\index.js:7:376640)
    at process.emit (events.js:327:22)
    at processPromiseRejections (internal/process/promises.js:209:33)
0/1 / ▐▨▨▨▨▨╌╌╌╌╌▌ Encoding (6 threads)
 45.png: 35.92MB
```


When I was testing other formats this error happened with this image
![image](https://user-images.githubusercontent.com/50336793/102899695-17a6ad00-444a-11eb-80af-58eb0b93c994.png)

OxiPNG in this configuration takes hours to load
with an i5 8500 CPU
and a Radeon R5 430


```
npx @squoosh/cli --oxipng '{"level":3}'
```

**Comment by surma** [comment] 2020-12-22 16:48
So yeah, OxiPNG being slow on a 7159 x 4742‬ image is expected. If you use the PWA, it will use threads for OxiPNG. The CLI doesn’t do that yet. But PNG is a horrible format for big images anyway.

Overall the issue here is actually not the size of the image in general, but only in the context of JPEG-XL. And that codec is still unstable. I am going to close this as there is not much to do on our end except wait that the JPEG-XL encoder stabilizes.

**Closed as completed by surma** 2020-12-22 16:48 UTC

**Comment by Slender1808** [comment] 2020-12-22 16:56
this 37 MB image with wp2 was about 11 MB
