### ISSUE TITLE
Publish wasm libraries to npm

### ISSUE THREAD

**Issue by tracker1** [GoogleChromeLabs/squoosh#684] opened 2019-08-19 17:10 UTC
It would be nice to see each of the enc/dec libraries published in npm... perhaps in an @squoosh org.  This way other projects could make use of the output.  Would work to ensure an interface for both node and browser.

This should also include more documentation on how to use each library separately.  Also, publishing a merged library as a single entry point.

Doing the above would allow an easier integration for creating services that could utilize the libraries in question.  I know one could simply fork this repo, and bring out the docker build scripts, etc.  However by publishing from this repository, it would limit variance on the upstream packages to downstream systems.

**Comment by surma** [comment] 2019-08-19 17:20
cc @RReverser Do you have any interest in doing this at some point?

**Comment by RReverser** [comment] 2019-08-19 21:36
I actually asked @jakearchibald earlier whether this was considered. I think it could be useful, but wouldn't necessarily assign this to me yet. That said, PRs are welcome and I'd be happy to review :)

**Comment by surma** [comment] 2019-08-21 19:00
Dupe of #280 Actually

**Closed by surma** 2019-08-21 19:00 UTC
