### ISSUE TITLE
Some help / Better docs / Usage examples needed.

### ISSUE THREAD

**Issue by K0-RR** [GoogleChromeLabs/squoosh#1121] opened 2021-08-15 14:36 UTC
I tried `squoosh-cli --oxipng -arvZt8 -o max --strip all --fix 'dir'` and got `error: unknown option '-arvZt8'`.
Then tried `squoosh-cli --oxipng [-arvZt8 -o max --strip all --fix] 'dir'` - `error: unknown option '-o'`.

Using oxipng standalone like that (`oxipng -arvZt8 -o max --strip all --fix 'dir'`) works fine.

What did I do wrong?

**Comment by surma** [comment] 2021-08-15 21:55
Closing this as it’s effectively a dupe of #900.

Squoosh is not the same as OxiPNG, just uses OxiPNG under the hood. For an example invocation of the CLI, I recommend using the [web app](https://squoosh.app) and clicking the “Copy NPX command” button:

<img width="301" alt="Screenshot 2021-08-15 at 22 53 11" src="https://user-images.githubusercontent.com/234957/129493904-2547548f-6d34-4f28-beb9-4c130d9c6e41.png">

That will put a command in your clipboard, showing you how to use OxiPNG in the Squoosh CLI:

```
npx @squoosh/cli --oxipng '{"level":2,"interlace":false}'
```

**Closed as completed by surma** 2021-08-15 21:55 UTC
