### ISSUE TITLE
[Feature Request] Possibility to Remove Background of an Image

### ISSUE THREAD

**Issue by rahulshyokand** [GoogleChromeLabs/squoosh#915] opened 2020-12-17 07:32 UTC
**Is your feature request related to a problem? Please describe.**
While Resizing an image sometimes it's great to have the background removed and get the image converted to a transparent png image.

**Describe the solution you'd like**
The Background of the file removal can make the image size even smaller and will add a new feature to the project.

**Does other services/app have this feature?**
https://www.remove.bg/ has a similar feature.

**Comment by surma** [comment] 2020-12-17 17:00
Duplicate of #736

**Closed as completed by surma** 2020-12-17 17:00 UTC
