### ISSUE TITLE
Possible support for GIF

### ISSUE THREAD

**Issue by sja1n** [GoogleChromeLabs/squoosh#361] opened 2018-12-07 10:39 UTC
Can we have support for gif as well ?

**Describe the solution you'd like**
Compressing gifs should be similar i my knowledge as there are services from where images can be extracted from gifs and probably compressed/optimised and then can be stitched back together to ake gif again. 

**Does other service/app have this feature?**
for extracting the images out of gif [ezgif](https://ezgif.com/split) and for making gif from images [ezgif gifmaker](https://ezgif.com/maker)

**Comment by jakearchibald** [comment] 2018-12-07 10:40
Is it animated gifs you're interested in compresing, or just static ones?

**Comment by sja1n** [comment] 2018-12-07 10:49
just static ones

**Comment by jakearchibald** [comment] 2018-12-07 11:11
That's a lot easier in our current architecture 😄. 

I think this is a duplicate of https://github.com/GoogleChromeLabs/squoosh/issues/10.

(however, I don't think gif is ever smaller than png)

**Closed by jakearchibald** 2018-12-07 11:11 UTC
