### ISSUE TITLE
On big image - crash

### ISSUE THREAD

**Issue by barna21** [GoogleChromeLabs/squoosh#272] opened 2018-11-13 14:11 UTC
when upload  image file 8mb, webpage crash...

**Comment by temran** [comment] 2018-11-14 10:14
Reproducable crash of Chrome Version 70.0.3538.102 (Offizieller Build) (64-Bit), Windows 10 Pro 64 bit - November 13, 2018—KB4467708 (OS Build 17763.134), Memory 16 GB, Nvidia GTX 680, latest Driver
with big jpg-image of 73,4 MB.
File cannot be attached: "Yowza, that's a big file. Try again with a smaller file than 10 MB."
Would be helpful to give this information on the Homepage.

**Comment by kosamari** [comment] 2021-07-01 16:21
Closing this issue since it's been open for long time. consolidate to large photo issue to #298

**Closed by kosamari** 2021-07-01 16:21 UTC
Labels: bug
