### ISSUE TITLE
[CLI] Batch image compression.

### ISSUE THREAD

**Issue by sobujbd** [GoogleChromeLabs/squoosh#916] opened 2020-12-17 13:13 UTC
I'm trying compress all of image in a folder at once.

So, I've execute this command,
```
squoosh-cli --mozjpeg '{"quality":75,"baseline":false,"arithmetic":false,"progressive":true,"op timize_coding":true,"smoothing":0,"color_space":3,"quant_table":3,"trellis_multipass":false,"trel lis_opt_zero":false,"trellis_opt_table":false,"trellis_loops":1,"auto_subsample":true,"chroma_sub sample":2,"separate_chroma_quality":false,"chroma_quality":75}' -d output ./*
```

After that **Squoosh** start compressing the folder images. It's nicely showing 1.2.3.4.5.6..../17 - image decoding... 
But in few seconds, it's gives error and stack on decoding screen.

```
[Error: EISDIR: illegal operation on a directory, read] {
  errno: -4068,
  code: 'EISDIR',
  syscall: 'read'
}
Worker error:  Error [RuntimeError]: abort(Error: EISDIR: illegal operation on a directory, read). Build with -s ASSERTIONS=1 for more info.
    at process.w (\npm\node_modules\@squoosh\cli\build\index.js:7:376640)
    at process.emit (events.js:327:22)
    at processPromiseRejections (internal/process/promises.js:209:33)
    at processTicksAndRejections (internal/process/task_queues.js:98:32)
```

---
 - Squoosh CLI version: 0.5.0
 - OS w/ version: Windows 8
 - Node version: v12.18.2
 - npm version: 6.14.9

**Comment by surma** [comment] 2020-12-17 17:02
Yeah, I have heard that the CLI is currently causing problems on Windows. I’ll look into this.

**Comment by wokalek-work** [comment] 2020-12-22 16:36
Same for me
```
$ npx @squoosh/cli --mozjpeg '{quality:68}' images-src/ru -d ./images-build/ru2
0/1 | ▐╌╌╌╌╌╌╌╌╌╌▌ Decoding...
Worker error:  [Error: EISDIR: illegal operation on a directory, read] {
  errno: -4068,
  code: 'EISDIR',
  syscall: 'read'
0/1 \ ▐╌╌╌╌╌╌╌╌╌╌▌ Decoding...
```

Windows 10.
Node v14.15.1
Squoosh CLI version: 0.6.0

**Comment by DetachHead** [comment] 2020-12-27 03:23
this seems to be caused by passing`./*` in directories with directories in them, not windows-specific (though i don't think `./*` even expands on windows. see #923)

**Comment by braebo** [comment] 2021-01-03 03:33
Same issue here on MacOS

**Comment by surma** [comment] 2021-01-03 11:38
@FractalHQ how are you calling the CLI? MacOS works well for me.

**Comment by braebo** [comment] 2021-01-03 17:00
@surma I had neglected to specify the filetype after the wildcard!  It works now (albiet only locally with `squoosh-cli`, @npx seems to encounter the aforementioned issue regardless).

While the cli always stops responding after 16/22 images, it seems to output all of the new images successfully.

![squoosh](https://user-images.githubusercontent.com/55504972/103484228-174bd180-4dbb-11eb-948f-81168ca37c22.png)

**Comment by surma** [comment] 2021-01-06 11:04
@FractalHQ All of that should be solved with v0.6.1

@sobujbd Can you test if v0.6.1 works on Windows now?

**Comment by sobujbd** [comment] 2021-01-06 12:53
@surma I confirm that the version **v0.6.1** of **@squoosh/cli** working good on my WinPC. I got very smooth results on batch images compressing by using Squoosh CLI. :heart: 

Now @FractalHQ can make sure it works well on MacOS!

Off-topic : Here what is standing by **Squoosh** words? How would it be if the command name renamed from `squoosh-cli` to just `squoosh` ?

**Comment by surma** [comment] 2021-01-06 13:51
Well, we also wanted to have a library at some point. And I wanted to have a `@squoosh` namespace on npm, so making `@squoosh/cli` install as just `squoosh` seemed confusing.

I’m gonna close this as I know this works on MacOS :D

**Closed as completed by surma** 2021-01-06 13:51 UTC

**Comment by LucaDCS** [comment] 2021-07-28 20:34
For me, works without the star, just like these: 

npx @squoosh/cli --mozjpeg {"quality":60} -d NEW ./

![image](https://user-images.githubusercontent.com/77304273/127391713-01318ae3-cd92-46e5-a5fc-5a3db2d79d3d.png)
![image](https://user-images.githubusercontent.com/77304273/127391735-a2766d85-6a73-438e-b5e9-4cfca169bad5.png)
Windows 10.
Node v14.15.1
Squoosh CLI version:  v0.7.2

**Comment by LucaDCS** [comment] 2021-07-28 20:55
For me works without the star, just like these: 

npx @squoosh/cli --mozjpeg '{"quality":60}' -d NEW ./

![image](https://user-images.githubusercontent.com/77304273/127394406-f06ef2da-9f61-49d8-92d9-689a68757fb9.png)

To do it from .bat you have to do it without the single quotes, like this:

npx @squoosh/cli --mozjpeg {"quality":60} -d NEW ./
![image](https://user-images.githubusercontent.com/77304273/127394602-c211e4e9-d671-4e99-8a83-ad9a68ccdfb3.png)

Windows 10.
Node v14.15.1
Squoosh CLI v0.7.2

**Comment by LucaDCS** [comment] 2021-07-28 21:00
For me works without the star, just like these:

npx @squoosh/cli --mozjpeg '{"quality":60}' -d Squooshed ./

![image](https://user-images.githubusercontent.com/77304273/127395223-c0ffef4d-9807-4da4-962a-c84dd3a53ec0.png)

BTW, To do it from .bat you have to do it without the single quotes, like this:

npx @squoosh/cli --mozjpeg {"quality":60} -d Squooshed./
![image](https://user-images.githubusercontent.com/77304273/127395182-3dc107ce-b9f0-47fb-abb2-8d2b0a6c4d4d.png)

Windows 10.
Node v14.15.1
Squoosh CLI v0.7.2

**Comment by LucaDCS** [comment] 2021-07-28 21:02
For me works without the star, just like these:

npx @squoosh/cli --mozjpeg '{"quality":60}' -d Squooshed ./

![image](https://user-images.githubusercontent.com/77304273/127395475-ceb8c9c7-f9a1-43c2-aff1-ac19e35f8a0d.png)

BTW, To do it from .bat you have to do it without the single quotes, like this:

npx @squoosh/cli --mozjpeg {"quality":60} -d Squooshed ./

![image](https://user-images.githubusercontent.com/77304273/127395489-ce804323-0fdf-486f-ba55-e0ef59679801.png)

Windows 10.
Node v14.15.1
Squoosh CLI v0.7.2

**Comment by dev0652** [comment] 2022-09-27 08:21
@LucaDCS,
Thank you, your solution worked for me, too.

**Comment by dev0652** [comment] 2022-09-27 09:08
@surma,

two issues: 

1. 
Specifying all files in a directory as `*.jpg` used to work before, but now it produces the following error: 

![Знімок екрана 2022-09-27 103119](https://user-images.githubusercontent.com/113797010/192474305-ed5f05c1-6143-4550-abea-c347a2d811f9.png)

Same thing happens when I try  `./*.jpg`. Is this intended behavior?

2. 
When I run the command from PowerShell, it works OK. But when I try to run it from a .bat file, I get the 'The system cannot find the path specified' error (regardless of whether quotes are or are not there) and the resulting folder turns out to be empty.

Windows 11
Node v16.17.1
Squoosh CLI v8.15.0
